# version: '3.8'

services:
  # php service container
  laravel_apis_app:
    build:
      args:
        user: laravel_apis_user
        uid: 1000
      context: ./
      dockerfile: DockerFile
    image: laravel_apis_app_image
    container_name: laravel_apis_app
    restart: unless-stopped  #or always
    # depends_on:
    #   - laravel_apis_app_mysql
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_apis_app_network
  #nginx service
  laravel_apis_webserver:
    platform: linux/amd64
    image: nginx:alpine
    container_name: laravel_apis_webserver_container
    restart: unless-stopped
    ports: 
      - "6162:80" #6162 outside the container, port 80 inside the container
    networks:
      - laravel_apis_app_network

networks: 
  laravel_apis_app_network:
    driver: bridge